package src

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"os"
	"io"
	"net/http"
)

/*

Pulling an Image Manifest:
		The image manifest can be fetched with the following url:
			GET /v2/<name>/manifests/<reference>

Pulling a Layer:
		Layers are stored in the blob portion of the registry, keyed by digest. Pulling a layer is carried out by a standard http request. The URL is as follows:
			GET /v2/<name>/blobs/<digest> ---> digest is of the form sha256

*/

// --------------------------------------------------------------Authentication---------------------------------------------------------------------------


type Img_Layer struct{
	MediaType string `json:"mediaType"`
	Digest    string `json:"digest"`
	Size      int    `json:"size"`
}
type Img_Manifest struct { //generated by converting json to go (https://transform.tools/json-to-go)
	SchemaVersion int    `json:"schemaVersion"`
	MediaType     string `json:"mediaType"`
	Config        struct {
		MediaType string `json:"mediaType"`
		Digest    string `json:"digest"`
		Size      int    `json:"size"`
	} `json:"config"`
	Layers []Img_Layer `json:"layers"`
}

type TokenResponse struct {
	Token string `json:"token"`
}

type Manifestslist struct { //generated by converting json to go (https://transform.tools/json-to-go)
	Manifests []struct {
		Annotations struct {
			ComDockerOfficialImagesBashbrewArch string    `json:"com.docker.official-images.bashbrew.arch"`
			OrgOpencontainersImageBaseName      string    `json:"org.opencontainers.image.base.name"`
			OrgOpencontainersImageCreated       time.Time `json:"org.opencontainers.image.created"`
			OrgOpencontainersImageRevision      string    `json:"org.opencontainers.image.revision"`
			OrgOpencontainersImageSource        string    `json:"org.opencontainers.image.source"`
			OrgOpencontainersImageURL           string    `json:"org.opencontainers.image.url"`
			OrgOpencontainersImageVersion       string    `json:"org.opencontainers.image.version"`
		} `json:"annotations"`
		Digest    string `json:"digest"`
		MediaType string `json:"mediaType"`
		Platform  struct {
			Architecture string `json:"architecture"`
			Os           string `json:"os"`
		} `json:"platform"`
		Size int `json:"size"`
	} `json:"manifests"`
	MediaType     string `json:"mediaType"`
	SchemaVersion int    `json:"schemaVersion"`
}

// check if you re authorized to authenticate.
func Check_endpoint(name string) map[string]string {
	full_path := fmt.Sprintf("https://registry-1.docker.io/v2/%s/tags/list", name)
	resp, err := http.Get(full_path) //Check that the endpoint implements Docker Registry API V2.
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	//mimic the -i flag result. --> outputs a map with keys Bearer realm, scope and service.
	//for name, values := range resp.Header {
	m := make(map[string]string)
	authHeader := resp.Header.Get("Www-Authenticate")

	trimmedHeader := strings.TrimPrefix(authHeader, "Bearer ")
	pairs := strings.Split(trimmedHeader, ",")
	for _, pair := range pairs {
		kv := strings.Split(pair, "=")
		if len(kv) == 2 {
			key := strings.TrimSpace(kv[0])
			val := strings.Trim(strings.TrimSpace(kv[1]), "\"")
			m[key] = val
		}
	}
	return m
	//body, _ := io.ReadAll(resp.Body)
	//return string(body)
}

//If not, ask for a token.

func Request_token(attrs map[string]string) string {
	//The blueprint for requesting a token(supposi que 3and www headers.) --> The_val_of_bearer_realm + "?" +"service=" + The_val_of_service + "&" + "scope=" + val_of_repository
	full_path := fmt.Sprintf("%s?service=%s&scope=%s", attrs["realm"], attrs["service"], attrs["scope"])
	//i need to delete the "'s
	full_path = strings.ReplaceAll(full_path, `"`, "")
	resp, err := http.Get(full_path) //Check that the endpoint implements Docker Registry API V2.
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	var tokenRes TokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenRes); err != nil {
		panic(err)
	}

	return tokenRes.Token
}

func Authenticate(name string) int {
	if !strings.Contains(name, "/") {
		name = "library/" + name
	}
	m := Check_endpoint(name)
	token := Request_token(m)
	full_path := fmt.Sprintf("https://registry-1.docker.io/v2/%s/tags/list", name)
	req, err := http.NewRequest("GET", full_path, nil)
	if err != nil {
		panic(err)
	}

	// 2. Set the headers (equivalent to -H)
	req.Header.Set("Authorization", "Bearer "+token)
	// 3. Send the request
	client := &http.Client{}
	resp, err := client.Do(req)
	return resp.StatusCode
}

func Manifest(name, tag string) string { //a function for pulling an image manifest. (ref must be a tag. return is a sha256)
	if !strings.Contains(name, "/") {
		name = "library/" + name
	}
	m := Check_endpoint(name)
	token := Request_token(m)
	full_path := fmt.Sprintf("https://registry-1.docker.io/v2/%s/manifests/%s", name, tag)
	req, err := http.NewRequest("GET", full_path, nil)
	if err != nil {
		panic(err)
	}

	// 2. Set the headers (equivalent to -H)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.docker.distribution.manifest.v2+json")
	// 3. Send the request
	client := &http.Client{}
	resp, err := client.Do(req)
	// Assume rc is your io.ReadCloser

	/*
		bodyBytes, err := io.ReadAll(resp.Body)
		if err != nil {
			panic(err)
		}
	*/
	//convert the response body to json.
	var data Manifestslist
	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&data); err != nil {
		panic(err)
	}
	defer resp.Body.Close() // Always close the ReadCloser to avoid leaks

	//bodyString := string(bodyBytes)

	/*
		By default, the Docker daemon automatically detects the operating system (OS) and CPU architecture of the host machine where it is running.
		It scans the platform object within the manifest list for an entry that matches its own runtime environment (e.g., linux/amd64 or linux/arm64).
		Once a match is found, Docker uses the specific digest associated with that platform entry to fetch the actual image manifest and its corresponding layers.
	*/

	//i must choose the sha256 for my laptop.
	//i ll use the linux os and x86_64(amd64) as the default. (compatible with my laptop)
	//i ll traverse the manifests
	shaa256 := ""
	for i, u := range data.Manifests {
		if (u.Platform.Architecture == "amd64") && (u.Platform.Os == "linux") {
			shaa256 = data.Manifests[i].Digest
			break
		}
	}
	return shaa256
}

func Manifest_sha256(name, digest string) []Img_Layer{
	if !strings.Contains(name, "/") {
		name = "library/" + name
	}
	m := Check_endpoint(name)
	token := Request_token(m)
	full_path := fmt.Sprintf("https://registry-1.docker.io/v2/%s/manifests/%s", name, digest)
	req, err := http.NewRequest("GET", full_path, nil)
	if err != nil {
		panic(err)
	}

	// 2. Set the headers (equivalent to -H)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.docker.distribution.manifest.v2+json")
	// 3. Send the request
	client := &http.Client{}
	resp, err := client.Do(req)

	var data Img_Manifest
	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&data); err != nil {
		panic(err)
	}
	defer resp.Body.Close() 
	return data.Layers
}

func Manifest_sha(name, ref string) []Img_Layer{
	sha_str := Manifest(name, ref)
	img_lyr := Manifest_sha256(name, sha_str)
	return img_lyr
}

func Pull_layers(name string , layers []Img_Layer) {		//GET /v2/<name>/blobs/<digest>
	if !strings.Contains(name, "/") {
		name = "library/" + name
	}
	out, _ := os.Create("layer.tar.gz")
	defer out.Close()
	m := Check_endpoint(name)
	token := Request_token(m)
	for _, u := range layers{
		full_path := fmt.Sprintf("https://registry-1.docker.io/v2/%s/blobs/%s", name, u.Digest)
		req, err := http.NewRequest("GET", full_path, nil)
		if err != nil {
			panic(err)
		}

		// 2. Set the headers (equivalent to -H)
		req.Header.Set("Authorization", "Bearer "+token)
		// 3. Send the request
		client := &http.Client{}
		resp, err := client.Do(req)
		if err != nil {
    		panic(err)
		}
		defer resp.Body.Close() // Essential for connection reuse
		io.Copy(out, resp.Body)
	}
}


//i need to go back to https://distribution.github.io/distribution/spec/api/
